#!/bin/bash

#source ~/foam/foam-extend-4.0/etc/bashrc

#apps="haemoSimpleFoam haemoPisoFoam haemoPimpleFoam haemoPostProcess"
apps="haemoPimpleFoam"
libs="KriegerDougherty Krieger5 Quemada Carreau"

for app in $apps; do
	cd $app
	wmake
	cd ..
done

for lib in $libs; do
	cd $lib
	wmake libso
	cd ..
done
