#!/bin/bash

if [ ! $FOAM_USER_APPBIN ]; then
    FOAM_USER_APPBIN = $FOAM_SITE_APPBIN
    FOAM_USER_LIBBIN = $FOAM_SITE_LIBBIN
fi

#source ~/foam/foam-extend-4.0/etc/bashrc

apps="haemoPimpleFoam haemoSimpleFoam haemoPostProcess"
libs="KriegerDougherty Krieger5 Quemada Carreau Yeleswarapu splitFlowRateOutletVelocity"

for app in $apps; do
	cd $app
	wmake
	cd ..
done

for lib in $libs; do
	cd $lib
	wmake libso
	cd ..
done
